name: Automating Ngnix deployment with github actions

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Build Docker Image
        run: docker build -t nginx:latest ./kamal

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Debug ECR Registry
        run: echo "ECR_REGISTRY is ${{ steps.login-ecr.outputs.registry }}"

      - name: Tag Docker Image for ECR
        run: |
          docker tag nginx:latest ${{ steps.login-ecr.outputs.registry }}/kamalraj/ngnix:latest

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/kamalraj/ngnix:latest
      
      - name: SSH into Ec2 instance 
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT || '22' }}
          script: |
            IMAGE="${{ steps.login-ecr.outputs.registry }}/kamalraj/ngnix:latest"
            echo "Pulling image: $IMAGE"
            sudo docker pull $IMAGE
            sudo docker stop app || true
            sudo docker rm app || true
            sudo docker run -d --name app -p 80:80 nginx:latest

